---
title: "Meta-Analysis Notebook v2, Moderation Analya\sis"
output:
  html_notebook: default
  html_document: default
  pdf_document: default
---
```{r echo=FALSE, include = FALSE}
wd = "/home/bearry/DataAnalysis/Meta-Analysis/"
setwd(wd)
#Library import, data cleaning
library("compute.es")
library("metafor")
library("MAd")
library("meta")
library("ggplot2")
library("plotly")
library("tidyr")
source("R/utils.R") #contains several meta-related functions to be used
source("R/n-age-separator.R")
filename = "Data/MBI on Cognitive Functions (additional articles) V7.csv"
cols.to.use = c("ID","Author","Year","Title","Type","Task","Variable","Inclusion..1..Yes..2..No.", "Sample","Total.N...Mean.Age.","Total.N...Mean.Age.", "nT", "nC", "Num_Session", "Treat_Duration_Hour","Home_Duration_Hour","Mean_Post_T","SD_Post_T","Mean_Post_C","SD_Post_C","Task_Value")
data <- read.csv(filename, stringsAsFactors = FALSE, sep = ",")[,cols.to.use]
colnames(data)[colnames(data) == 'Total.N...Mean.Age.'] = "N"
colnames(data)[colnames(data) == 'Total.N...Mean.Age..1'] = "Mean Age"
colnames(data)[colnames(data) == 'Inclusion..1..Yes..2..No.'] = "Inclusion"
to.use <- which(data[,"Inclusion"] == 1)
data <- data[to.use,]
data$Type = toupper(data$Type)
for (i in 1:length(data[,"N"])){
  N_age = suppressWarnings(getN_Age(data,"N",i))
  data[i,"N"] = N_age[2]
  data[i,"Mean Age"] = N_age[3]
}
data <- data %>% drop_na(`Mean Age`)
#Data saved as characters, this converts them to numeric values
for (i in 10:21){ ##START AT 10
 data[,i] <- suppressWarnings(as.numeric(data[,i]))
}

#Alter means based on polarity
meanCols = c(17,19)
data[,meanCols] = data[,meanCols] * data$Task_Value
```
This table lists the occurences of each Types
```{r}
#count occurences of each Type
for(i in 1:length(data$Type))
     {
  if (data$Type[i] == "EF-INHIBOTORY CONTROL" | data$Type[i] =="EF - INHIBITORY CONTROL")
    {
      data$Type[i] = "EF-INHIBITORY CONTROL"
  }
   
  else if (data$Type[i] == "AT - SUSTAINED" | data$Type[i] == "AT- SUSTAINED")
  {
    data$Type[i] = "AT-SUSTAINED"
  }
  else if (data$Type[i] == "AT - SELECTIVE")
  {
    data$Type[i] = "AT-SELECTIVE"
  }
  else if (data$Type[i] == "EF - PLANNING AND PROBLEM-SOLVING")
  {
    data$Type[i] = "EF - PLANNING"
  }
  else if (data$Type[i] == "EF - COGNITIVE FLEXIBILITY")
  {
    data$Type[i] = "EF-COGNITIVE FLEXIBILITY"
  }
  else if (data$Type[i] == "EF - CONFLICT MONITORING")
  {
    data$Type[i] = "EF-CONFLICT MONITORING"
  }
}
library(data.table)
data.table(data$Type)[,.N,by=data$Type]
name <- data.table(data$Type)[,.N,by=data$Type]$data
```
```{r}
#Splitting data into age range bins b1, b2, b3
#with b1 contains ages below 30, b2 between 30 and 50, b3 above 50
bin1 <- data[(data$`Mean Age` < 30),]
bin2 <- data[(30 <= data$`Mean Age` & data$`Mean Age` <= 50),]
bin3 <- data[(data$`Mean Age` > 50),]

```